name: hamster
on:
  push:
    branches:
      - update-hamster
jobs:
  release-build:
    strategy:
      matrix:
        platform: [ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: cargo install
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustc --version
          rustup default stable
          rustup update
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
      - name: cargo build
        run: |
          cargo build --release
      - name: build docker
        run: |
          cd target/release
          docker build -t hamstershare/hamster:dev  -f  ../../scripts/ci/docker/substrate.Dockerfile .
          docker push hamstershare/hamster:dev
